"""add_openclaw_v2_orchestrator_tables

Revision ID: 61f2b2393b09
Revises: e23726a6b99e
Create Date: 2026-03-31 05:00:07.048379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f2b2393b09'
down_revision: Union[str, Sequence[str], None] = 'e23726a6b99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_category', 'events', ['category'], unique=False)
    op.create_index('idx_events_category_source', 'events', ['category', 'source_id'], unique=False)
    op.create_index('idx_events_created', 'events', ['created_at'], unique=False)
    op.create_index('idx_events_source', 'events', ['source_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nodes_created', 'nodes', ['created_at'], unique=False)
    op.create_index('idx_nodes_properties', 'nodes', ['properties'], unique=False, postgresql_using='gin')
    op.create_index('idx_nodes_type', 'nodes', ['type'], unique=False)
    op.create_index('idx_nodes_type_status', 'nodes', ['type', 'status'], unique=False)
    op.create_table('birka_fleet',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('spawn_depth', sa.Integer(), nullable=False),
    sa.Column('parent_instance_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['parent_instance_id'], ['birka_fleet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_index('idx_fleet_last_heartbeat', 'birka_fleet', ['last_heartbeat'], unique=False)
    op.create_index('idx_fleet_node', 'birka_fleet', ['node_id'], unique=False)
    op.create_index('idx_fleet_status', 'birka_fleet', ['status'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edges_source', 'edges', ['source_id'], unique=False)
    op.create_index('idx_edges_source_type', 'edges', ['source_id', 'type'], unique=False)
    op.create_index('idx_edges_target', 'edges', ['target_id'], unique=False)
    op.create_index('idx_edges_target_type', 'edges', ['target_id', 'type'], unique=False)
    op.create_index('idx_edges_type', 'edges', ['type'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('openclaw_id', sa.String(length=64), nullable=False),
    sa.Column('birka_instance_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_index('idx_missions_birka', 'missions', ['birka_instance_id'], unique=False)
    op.create_index('idx_missions_dispatched', 'missions', ['dispatched_at'], unique=False)
    op.create_index('idx_missions_priority_status', 'missions', ['priority', 'status'], unique=False)
    op.create_index('idx_missions_status', 'missions', ['status'], unique=False)
    op.create_table('control_commands',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('target_instance_id', sa.String(length=64), nullable=False),
    sa.Column('command_type', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['target_instance_id'], ['birka_fleet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commands_created', 'control_commands', ['created_at'], unique=False)
    op.create_index('idx_commands_status', 'control_commands', ['status'], unique=False)
    op.create_index('idx_commands_target', 'control_commands', ['target_instance_id'], unique=False)
    op.create_index('idx_commands_type', 'control_commands', ['command_type'], unique=False)
    op.create_table('resource_manifest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('capability_name', sa.String(length=100), nullable=False),
    sa.Column('capability_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('declared_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['birka_fleet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'capability_name', name='uq_instance_capability')
    )
    op.create_index('idx_manifest_capability', 'resource_manifest', ['capability_name'], unique=False)
    op.create_index('idx_manifest_instance', 'resource_manifest', ['instance_id'], unique=False)
    op.create_table('safeguard_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=True),
    sa.Column('safeguard_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['birka_fleet.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_safeguard_created', 'safeguard_events', ['created_at'], unique=False)
    op.create_index('idx_safeguard_instance', 'safeguard_events', ['instance_id'], unique=False)
    op.create_index('idx_safeguard_severity', 'safeguard_events', ['severity'], unique=False)
    op.create_index('idx_safeguard_type', 'safeguard_events', ['safeguard_type'], unique=False)
    op.create_table('spawn_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_instance_id', sa.String(length=64), nullable=False),
    sa.Column('child_instance_id', sa.String(length=64), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('spawn_reason', sa.Text(), nullable=True),
    sa.Column('mission_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_instance_id'], ['birka_fleet.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['parent_instance_id'], ['birka_fleet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spawn_child', 'spawn_tree', ['child_instance_id'], unique=False)
    op.create_index('idx_spawn_created', 'spawn_tree', ['created_at'], unique=False)
    op.create_index('idx_spawn_depth', 'spawn_tree', ['depth'], unique=False)
    op.create_index('idx_spawn_parent', 'spawn_tree', ['parent_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_spawn_parent', table_name='spawn_tree')
    op.drop_index('idx_spawn_depth', table_name='spawn_tree')
    op.drop_index('idx_spawn_created', table_name='spawn_tree')
    op.drop_index('idx_spawn_child', table_name='spawn_tree')
    op.drop_table('spawn_tree')
    op.drop_index('idx_safeguard_type', table_name='safeguard_events')
    op.drop_index('idx_safeguard_severity', table_name='safeguard_events')
    op.drop_index('idx_safeguard_instance', table_name='safeguard_events')
    op.drop_index('idx_safeguard_created', table_name='safeguard_events')
    op.drop_table('safeguard_events')
    op.drop_index('idx_manifest_instance', table_name='resource_manifest')
    op.drop_index('idx_manifest_capability', table_name='resource_manifest')
    op.drop_table('resource_manifest')
    op.drop_index('idx_commands_type', table_name='control_commands')
    op.drop_index('idx_commands_target', table_name='control_commands')
    op.drop_index('idx_commands_status', table_name='control_commands')
    op.drop_index('idx_commands_created', table_name='control_commands')
    op.drop_table('control_commands')
    op.drop_index('idx_missions_status', table_name='missions')
    op.drop_index('idx_missions_priority_status', table_name='missions')
    op.drop_index('idx_missions_dispatched', table_name='missions')
    op.drop_index('idx_missions_birka', table_name='missions')
    op.drop_table('missions')
    op.drop_index('idx_edges_type', table_name='edges')
    op.drop_index('idx_edges_target_type', table_name='edges')
    op.drop_index('idx_edges_target', table_name='edges')
    op.drop_index('idx_edges_source_type', table_name='edges')
    op.drop_index('idx_edges_source', table_name='edges')
    op.drop_table('edges')
    op.drop_index('idx_fleet_status', table_name='birka_fleet')
    op.drop_index('idx_fleet_node', table_name='birka_fleet')
    op.drop_index('idx_fleet_last_heartbeat', table_name='birka_fleet')
    op.drop_table('birka_fleet')
    op.drop_index('idx_nodes_type_status', table_name='nodes')
    op.drop_index('idx_nodes_type', table_name='nodes')
    op.drop_index('idx_nodes_properties', table_name='nodes', postgresql_using='gin')
    op.drop_index('idx_nodes_created', table_name='nodes')
    op.drop_table('nodes')
    op.drop_index('idx_events_source', table_name='events')
    op.drop_index('idx_events_created', table_name='events')
    op.drop_index('idx_events_category_source', table_name='events')
    op.drop_index('idx_events_category', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
