"""add agent_id to memory_entry

Revision ID: 746b11927162
Revises: 61f2b2393b09
Create Date: 2026-05-09 05:49:04.160622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746b11927162'
down_revision: Union[str, Sequence[str], None] = '61f2b2393b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_entry', sa.Column('agent_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_memory_entry_agent_id'), 'memory_entry', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_entry_agent_id'), table_name='memory_entry')
    op.drop_column('memory_entry', 'agent_id')
    # ### end Alembic commands ###
