"""Initial memory vault schema

Revision ID: e23726a6b99e
Revises: 
Create Date: 2026-03-29 09:15:34.489536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23726a6b99e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('compacted_into', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compacted_into'], ['memory_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('entry_ids', sa.JSON(), nullable=False),
    sa.Column('memory_md_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compaction_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('merged_ids', sa.JSON(), nullable=False),
    sa.Column('compacted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['memory_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compaction_index')
    op.drop_table('snapshot_index')
    op.drop_table('memory_entry')
    # ### end Alembic commands ###
